# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mohamedcreditp7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mohamedcreditp7.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0dcc9682bc974f6286adc3d8276d2a68 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f97005215e84fb8a5142188c32437f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mohamedcreditp7.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0dcc9682bc974f6286adc3d8276d2a68 }}/mon_image_athir2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mohamedcreditp7'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_714a4f4fb777444bb953a488e11d0b73 }}
        images: 'mohamedcreditp7.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0dcc9682bc974f6286adc3d8276d2a68 }}/mon_image_athir2:${{ github.sha }}'